version: "3.9"
services:
  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: pantrynode
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
    container_name: db
    networks:
      - local
  node:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    depends_on:
      - db
    restart: always
    ports:
      - "3000:3000"
      - "3001:3001"
    networks:
      - local
networks:
  local: